apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-worker
  labels:
    app: autoscale-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale-worker
  template:
    metadata:
      labels:
        app: autoscale-worker
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8080'
    spec:
      containers:
        - image: "autoscale-worker"
          name: autoscale-worker
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: autoscale-worker-config
          imagePullPolicy: Never